@url=http://localhost:8080

################################################################
POST {{url}}/api/admin/login
Content-Type: application/json

{
    "id":"admin",
    "password":"123456"
}



#####
POST {{url}}/posts
Content-Type: application/json

{
    "id": 4,
    "title": "My test",
    "author": "10codeing"
}

##################
GET {{url}}/posts

#####
PUT {{url}}/posts/2
Content-Type: application/json

{
    "title": "New 22",
    "author": "iasdfasdfasdf"
}


#############
PATCH {{url}}/posts/2
Content-Type: application/json

{
    "title": "Patch 2"
}

#########
DELETE {{url}}/posts/4